algoritmo "nome_salario"
// Função :
// Autor : Tiago Raug
// Data : 19/10/2022
// Seção de Declarações 
var
   nome,mes:caractere
   salario:real
inicio
// Seção de Comandos 
   escreval("Nome do Funcionario : ")
   leia(nome)
   escreval("Salario: ")
   leia(salario)
   escreval("Digite o mes do ultimo salario: ")
   leia(mes)
   escreval("O funcionario: ",nome," tem um salario de R$",salario:5:2," no mes de ",mes )
fimalgoritmo
