algoritmo "doisnumeros_inteiros_soma"
// Função :
// Autor :
// Data : 19/10/2022
// Seção de Declarações 
var
   n1,n2:inteiro
   soma:real
inicio
// Seção de Comandos
   escreval("Digite um valor: ")
   leia(n1)
   escreval("Digite outro valor: ")
   leia(n2)
   soma<-(n1+n2)
   escreval("A soma entre ",n1," e",n2," é igual a: ",soma)
   escreval("  ")
   escreval(" FIM DO PROGRAMA ")
fimalgoritmo
