algoritmo "notas_media"
// Função :
// Autor :
// Data : 19/10/2022
// Seção de Declarações 
var
   n1,n2,media:real
inicio
// Seção de Comandos 
   escreval("Digite nota 1: ")
   leia(n1)
   escreval("Digite nota 2: ")
   leia(n2)
   media<-(n1+n2)/2
   escreval("Nota 1: ",n1:2:2)
   escreval("Nota 2: ",n2:2:2)
   escreval("a media entre ",n1," e ",n2," é igual a: ",media:2:2)
   escreval("  ")
   escreval("  FIM DO PROGRAMA ")
fimalgoritmo
