algoritmo "num_int_ante_pos"
// Função :
// Autor :
// Data : 19/10/2022
// Seção de Declarações 
var
   n1,ante,posterior:inteiro
inicio
// Seção de Comandos
   escreval("Digite um numero: ")
   leia(n1)
   ante<-(n1-1)
   posterior<-(n1+1)
   escreval("O antecessor de ",n1," é",ante)
   escreval("O sucessor de ",n1," é",posterior)
   escreval("  ")
   escreval("  FIM DO PROGRAMA  ")
fimalgoritmo
