algoritmo "dobro_terparte"
// Função :
// Autor :
// Data : 19/10/2022
// Seção de Declarações
var
   n1,dobro,terparte:real
inicio
// Seção de Comandos
   escreval("Digite um numero : ")
   leia(n1)
   dobro<-(n1*2)
   terparte<-(n1*(1/3))
   escreval("O dobro de ",n1," é:",dobro)
   escreval("A terca parte de ",n1," é:",terparte:2:5)
   escreval("  ")
   escreval("  FIM DO PROGRMA  ")
fimalgoritmo
