algoritmo "medidas"
// Função :
// Autor :
// Data : 19/10/2022
// Seção de Declarações 
var
   medida,km,hm,dam,m,dm,cm,mm:real
inicio
// Seção de Comandos 
   escreval("Digite uma distancia em metros: ")
   leia(medida)
   km<-(medida/1000)
   escreval("a distancia de ",medida," corresponde a:",km," kilometros")
   escreval("  ")
   escreval("a distancia de ",medida," corresponde a:",km," kilometros")
   escreval("  ")
   escreval(" FIM DO PROGRAMA ")
fimalgoritmo
